services:
  mimir:
    build:
      context: .
      dockerfile: ./crates/Dockerfile
    container_name: mimir
    volumes:
      - ./crates:/workspace/crates
      - ./Cargo.toml:/workspace/Cargo.toml
      - ./.claude:/root/.claude
    environment:
      CLAUDE_CONFIG_DIR: /root/.claude
    working_dir: /workspace
    tty: true
    stdin_open: true